
cd chap01
for %%x in (*.mak) do make -f %%x
cd ..

cd chap02
for %%x in (*.mak) do make -f %%x
cd ..

cd chap03
for %%x in (*.mak) do make -f %%x
cd ..

cd chap04
for %%x in (*.mak) do make -f %%x
cd ..

cd chap05
for %%x in (*.mak) do make -f %%x
cd ..

cd chap06
for %%x in (*.mak) do make -f %%x
cd ..

cd chap08
for %%x in (*.mak) do make -f %%x
cd ..

cd chap09
for %%x in (*.mak) do make -f %%x
cd ..

cd chap10
for %%x in (*.mak) do make -f %%x
cd ..

cd chap11
for %%x in (*.mak) do make -f %%x
cd ..

cd chap12
for %%x in (*.mak) do make -f %%x
cd ..

cd chap13
for %%x in (*.mak) do make -f %%x
cd ..

cd chap14
for %%x in (*.mak) do make -f %%x
cd ..

cd chap15
for %%x in (*.mak) do make -f %%x
cd ..

cd chap16
for %%x in (*.mak) do make -f %%x
cd ..

cd chap17
for %%x in (*.mak) do make -f %%x
cd ..

cd chap18
for %%x in (*.mak) do make -f %%x
cd ..

cd chap19
for %%x in (*.mak) do make -f %%x
cd ..
